//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pv239_project.Resources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pv239_project.Resources.i18n.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ChangePasswordPopup_CancelButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordPopup.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ChangePasswordPopup_SubmitButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordPopup.SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message. Please check your internet connection and try again..
        /// </summary>
        internal static string ConversationDetailPage_FailedToSendMessageError {
            get {
                return ResourceManager.GetString("ConversationDetailPage.FailedToSendMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load conversation. Please check your internet connection and try again..
        /// </summary>
        internal static string ConversationDetailPage_LoadingError {
            get {
                return ResourceManager.GetString("ConversationDetailPage.LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message....
        /// </summary>
        internal static string ConversationDetailPage_MessagePlaceholder {
            get {
                return ResourceManager.GetString("ConversationDetailPage_MessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ConversationDetailPage_SendButtonText {
            get {
                return ResourceManager.GetString("ConversationDetailPage.SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        internal static string ConversationListPage_PageLabel {
            get {
                return ResourceManager.GetString("ConversationListPage.PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password must be at least 6 characters long.
        /// </summary>
        internal static string CreateNewUserPage_ConfirmPasswordLengthError {
            get {
                return ResourceManager.GetString("CreateNewUserPage.ConfirmPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string CreateNewUserPage_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CreateNewUserPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string CreateNewUserPage_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the user. Please check internet connection and try again..
        /// </summary>
        internal static string CreateNewUserPage_GeneralError {
            get {
                return ResourceManager.GetString("CreateNewUserPage.GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all input fields.
        /// </summary>
        internal static string CreateNewUserPage_InputError {
            get {
                return ResourceManager.GetString("CreateNewUserPage.InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        internal static string CreateNewUserPage_PasswordLengthError {
            get {
                return ResourceManager.GetString("CreateNewUserPage.PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CreateNewUserPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string CreateNewUserPage_PasswordsNotSame {
            get {
                return ResourceManager.GetString("CreateNewUserPage.PasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string CreateNewUserPage_SignUpButtonText {
            get {
                return ResourceManager.GetString("CreateNewUserPage.SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string CreateNewUserPage_SurnamePlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string CreateNewUserPage_Title {
            get {
                return ResourceManager.GetString("CreateNewUserPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all input fields.
        /// </summary>
        internal static string LoginPage_EmptyFields {
            get {
                return ResourceManager.GetString("LoginPage.EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginPage_Form_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage.Form.EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_Form_LoginText {
            get {
                return ResourceManager.GetString("LoginPage.Form.LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        internal static string LoginPage_Form_NewAccountText {
            get {
                return ResourceManager.GetString("LoginPage.Form.NewAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_Form_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage.Form.PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while logging in. Please check your credentials and try again..
        /// </summary>
        internal static string LoginPage_GeneralError {
            get {
                return ResourceManager.GetString("LoginPage.GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or create a new account.
        /// </summary>
        internal static string LoginPage_LoginText {
            get {
                return ResourceManager.GetString("LoginPage.LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoginPage_WelcomeText {
            get {
                return ResourceManager.GetString("LoginPage.WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string SettingsPage_ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string SettingsPage_DeleteAccountButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.DeleteAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string SettingsPage_LogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.LogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new profile picture.
        /// </summary>
        internal static string SettingsPage_NewProfilePictureButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.NewProfilePictureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_PageLabel {
            get {
                return ResourceManager.GetString("SettingsPage.PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SettingsPage_SubmitButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UploadProfilePicturePopup_CancelButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a picture.
        /// </summary>
        internal static string UploadProfilePicturePopup_PickPictureButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.PickPictureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string UploadProfilePicturePopup_SubmitButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UserListPage_PageLabel {
            get {
                return ResourceManager.GetString("UserListPage.PageLabel", resourceCulture);
            }
        }
    }
}
