//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pv239_project.Resources.i18n {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("pv239_project.Resources.i18n.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginPage_WelcomeText {
            get {
                return ResourceManager.GetString("LoginPage.WelcomeText", resourceCulture);
            }
        }
        
        internal static string LoginPage_LoginText {
            get {
                return ResourceManager.GetString("LoginPage.LoginText", resourceCulture);
            }
        }
        
        internal static string LoginPage_Form_LoginText {
            get {
                return ResourceManager.GetString("LoginPage.Form.LoginText", resourceCulture);
            }
        }
        
        internal static string LoginPage_Form_NewAccountText {
            get {
                return ResourceManager.GetString("LoginPage.Form.NewAccountText", resourceCulture);
            }
        }
        
        internal static string LoginPage_Form_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage.Form.PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string LoginPage_Form_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage.Form.EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string ConversationDetailPage_SendButtonText {
            get {
                return ResourceManager.GetString("ConversationDetailPage.SendButtonText", resourceCulture);
            }
        }
        
        internal static string ConversationDetailPage_MessagePlaceholder {
            get {
                return ResourceManager.GetString("ConversationDetailPage_MessagePlaceholder", resourceCulture);
            }
        }
        
        internal static string ConversationListPage_PageLabel {
            get {
                return ResourceManager.GetString("ConversationListPage.PageLabel", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.FirstNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_SurnamePlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.SurnamePlaceholder", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreateNewUserPage.ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string CreateNewUserPage_SignUpButtonText {
            get {
                return ResourceManager.GetString("CreateNewUserPage.SignUpButtonText", resourceCulture);
            }
        }
        
        internal static string SettingsPage_PageLabel {
            get {
                return ResourceManager.GetString("SettingsPage.PageLabel", resourceCulture);
            }
        }
        
        internal static string SettingsPage_ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.ChangePasswordButtonText", resourceCulture);
            }
        }
        
        internal static string SettingsPage_NewProfilePictureButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.NewProfilePictureButtonText", resourceCulture);
            }
        }
        
        internal static string SettingsPage_SubmitButtonText {
            get {
                return ResourceManager.GetString("SettingsPage.SubmitButtonText", resourceCulture);
            }
        }
        
        internal static string UserListPage_PageLabel {
            get {
                return ResourceManager.GetString("UserListPage.PageLabel", resourceCulture);
            }
        }
        
        internal static string ChangePasswordPopup_CancelButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordPopup.CancelButtonText", resourceCulture);
            }
        }
        
        internal static string ChangePasswordPopup_SubmitButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordPopup.SubmitButtonText", resourceCulture);
            }
        }
        
        internal static string UploadProfilePicturePopup_PickPictureButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.PickPictureButtonText", resourceCulture);
            }
        }
        
        internal static string UploadProfilePicturePopup_CancelButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.CancelButtonText", resourceCulture);
            }
        }
        
        internal static string UploadProfilePicturePopup_SubmitButtonText {
            get {
                return ResourceManager.GetString("UploadProfilePicturePopup.SubmitButtonText", resourceCulture);
            }
        }
    }
}
